import type { Config, Context } from "@netlify/functions";
import { getDatabase } from "@netlify/database";
import { getSessionUser } from "../lib/auth.js";
import { getPortfolioForUser } from "../lib/data.js";
import { json } from "../lib/http.js";

function decodeEntities(s:string){return s.replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,"$1").replace(/&amp;/g,"&").replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&lt;/g,"<").replace(/&gt;/g,">")}
function pickTag(xml:string,tag:string){const m=xml.match(new RegExp(`<${tag}[^>]*>([\\s\\S]*?)<\\/${tag}>`,`i`));return m?decodeEntities(m[1].trim()):""}
async function rssNews(symbols:string[]){if(!symbols.length)return [];const q=encodeURIComponent(symbols.slice(0,6).join(" OR ")+" investimentos");const url=`https://news.google.com/rss/search?q=${q}&hl=pt-BR&gl=BR&ceid=BR:pt-419`;try{const r=await fetch(url,{headers:{"user-agent":"Mozilla/5.0 PlataformaInvestimentos/1.0"},signal:AbortSignal.timeout(8000)});if(!r.ok)return [];const xml=await r.text();return [...xml.matchAll(/<item>([\s\S]*?)<\/item>/gi)].slice(0,8).map(m=>{const item=m[1];return {title:pickTag(item,"title"),url:pickTag(item,"link"),publishedAt:pickTag(item,"pubDate"),source:pickTag(item,"source")||"Google News"}}).filter(x=>x.title&&x.url)}catch{return []}}
async function dividends(symbols:string[],kind:"stocks"|"fii",token:string){if(!symbols.length)return [];const today=new Date(),end=new Date(today);end.setFullYear(end.getFullYear()+1);const fmt=(d:Date)=>d.toISOString().slice(0,10);const url=`https://brapi.dev/api/v2/${kind}/dividends?symbols=${encodeURIComponent(symbols.slice(0,20).join(","))}&startDate=${fmt(today)}&endDate=${fmt(end)}&sortBy=paymentDate&sortOrder=asc`;try{const r=await fetch(url,{headers:token?{Authorization:`Bearer ${token}`}:{},signal:AbortSignal.timeout(8000)});if(!r.ok)return [];const p:any=await r.json();const out:any[]=[];if(kind==="fii"&&Array.isArray(p?.dividends)){for(const ev of p.dividends){if(ev?.paymentDate)out.push({symbol:String(ev?.symbol||"").toUpperCase(),label:ev.label||"Rendimento",rate:Number(ev.rate)||0,paymentDate:String(ev.paymentDate).slice(0,10),lastDatePrior:ev.lastDatePrior||null,approvedOn:ev.approvedOn||null,source:"brapi.dev"});}}else{for(const result of (p?.results||[])){const symbol=result?.symbol||result?.requestedSymbol||"";const data=result?.data||result;const list=data?.cashDividends||data?.dividends||[];for(const ev of list){if(ev?.paymentDate)out.push({symbol,label:ev.label||ev.type||"Provento",rate:Number(ev.rate)||0,paymentDate:String(ev.paymentDate).slice(0,10),lastDatePrior:ev.lastDatePrior||null,approvedOn:ev.approvedOn||null,source:"brapi.dev"});}}}return out.sort((a,b)=>String(a.paymentDate).localeCompare(String(b.paymentDate))).slice(0,30)}catch{return []}}

export default async(req:Request,_context:Context)=>{if(req.method!=="GET")return json({error:"Método não permitido."},405);const user=await getSessionUser(req);if(!user)return json({error:"Sessão expirada."},401);const portfolio=await getPortfolioForUser(user);if(!portfolio)return json({error:"Carteira não encontrada."},404);const portfolioId=Number(portfolio.id),db=getDatabase();const assets=await db.sql`SELECT symbol,asset_class FROM assets WHERE portfolio_id=${portfolioId} AND active=TRUE ORDER BY symbol LIMIT 40` as any[];const symbols=[...new Set(assets.map(a=>String(a.symbol).toUpperCase()).filter(Boolean))];const stockSymbols=assets.filter(a=>["Ações BR","ETFs"].includes(String(a.asset_class))).map(a=>String(a.symbol).toUpperCase()).filter(Boolean);const fiiSymbols=assets.filter(a=>String(a.asset_class)==="FIIs").map(a=>String(a.symbol).toUpperCase()).filter(Boolean);const token=Netlify.env.get("BRAPI_TOKEN")||"";const [news,stockDiv,fiiDiv]=await Promise.all([rssNews(symbols),dividends(stockSymbols,"stocks",token),dividends(fiiSymbols,"fii",token)]);return json({requestedAt:new Date().toISOString(),news,dividends:[...stockDiv,...fiiDiv].sort((a,b)=>String(a.paymentDate).localeCompare(String(b.paymentDate))).slice(0,30),sources:{news:"Google News RSS",dividends:"brapi.dev",tokenConfigured:Boolean(token)},notes:{dividends:"Exibe somente eventos anunciados pela fonte. Não é previsão de dividendos futuros."}})};
export const config:Config={path:"/api/agenda"};
