import type { Config, Context } from "@netlify/functions";
import { getDatabase } from "@netlify/database";
import { getSessionUser } from "../lib/auth.js";
import { getPortfolioForUser, logActivity } from "../lib/data.js";
import { json } from "../lib/http.js";

const types=new Set(["move_abs","move_up","move_down","price_above","price_below"]);
const severities=new Set(["info","warning","critical"]);
const statuses=new Set(["WATCH","REVIEW","NO_ACTION","CLOSED"]);
function text(v:any,max:number){return String(v??"").slice(0,max);}
function iso(v:any){if(typeof v!=="string")return null;const d=new Date(v);return Number.isFinite(d.getTime())?d.toISOString():null;}
function num(v:any){const n=Number(v);return Number.isFinite(n)?n:null;}
function safeRules(v:any){if(!Array.isArray(v))return[];return v.slice(0,100).map((x:any,i:number)=>({id:text(x?.id||`rule-${i}`,120),symbol:text(x?.symbol||"IBOV",32).toUpperCase(),type:types.has(x?.type)?x.type:"move_abs",threshold:Math.max(0,num(x?.threshold)??0),severity:severities.has(x?.severity)?x.severity:"warning",name:text(x?.name,100),note:text(x?.note,400),enabled:x?.enabled!==false,triggered:x?.triggered===true,lastTriggeredAt:iso(x?.lastTriggeredAt),lastClearedAt:iso(x?.lastClearedAt),lastValue:num(x?.lastValue),updatedAt:iso(x?.updatedAt)})).filter((x:any)=>x.id&&x.symbol);}
function safeEvents(v:any){if(!Array.isArray(v))return[];return v.slice(0,100).map((x:any)=>({id:text(x?.id,180),ruleId:text(x?.ruleId,120),symbol:text(x?.symbol,32).toUpperCase(),ruleName:text(x?.ruleName,120),eventType:x?.eventType==="cleared"?"cleared":"triggered",severity:severities.has(x?.severity)?x.severity:"info",value:num(x?.value),threshold:num(x?.threshold),createdAt:iso(x?.createdAt)||new Date().toISOString()})).filter((x:any)=>x.id);}
function safeDecisions(v:any){if(!Array.isArray(v))return[];return v.slice(0,100).map((x:any)=>({id:text(x?.id,180),sourceType:x?.sourceType==="alert"?"alert":"monitor",sourceId:text(x?.sourceId,180),symbol:text(x?.symbol,32).toUpperCase(),title:text(x?.title,220),status:statuses.has(x?.status)?x.status:"WATCH",note:text(x?.note,1000),reviewDate:/^\d{4}-\d{2}-\d{2}$/.test(String(x?.reviewDate||""))?String(x.reviewDate):null,outcome:text(x?.outcome,1000),reviewedAt:iso(x?.reviewedAt),createdAt:iso(x?.createdAt)||new Date().toISOString(),updatedAt:iso(x?.updatedAt)||iso(x?.createdAt)||new Date().toISOString()})).filter((x:any)=>x.id&&x.title);
};

export default async(req:Request,_context:Context)=>{const user=await getSessionUser(req);if(!user)return json({error:"Sessão expirada."},401);const portfolio=await getPortfolioForUser(user);if(!portfolio)return json({error:"Carteira não encontrada."},404);const portfolioId=Number(portfolio.id),db=getDatabase();if(req.method==="GET"){const rows=await db.sql`SELECT rules,events,decisions,updated_at FROM live_monitoring_center WHERE portfolio_id=${portfolioId} LIMIT 1` as any[];const row=rows[0];return json({rules:safeRules(row?.rules),events:safeEvents(row?.events),decisions:safeDecisions(row?.decisions),updatedAt:row?.updated_at||null});}if(req.method==="PUT"){let body:any;try{body=await req.json();}catch{return json({error:"Dados inválidos."},400);}const rules=safeRules(body?.rules),events=safeEvents(body?.events),decisions=safeDecisions(body?.decisions);await db.sql`INSERT INTO live_monitoring_center(portfolio_id,rules,events,decisions,updated_at) VALUES(${portfolioId},${JSON.stringify(rules)}::jsonb,${JSON.stringify(events)}::jsonb,${JSON.stringify(decisions)}::jsonb,NOW()) ON CONFLICT(portfolio_id) DO UPDATE SET rules=EXCLUDED.rules,events=EXCLUDED.events,decisions=EXCLUDED.decisions,updated_at=NOW()`;await logActivity(portfolioId,"updated","live_monitoring_center","Live Monitoring",{rules:rules.length,events:events.length,decisions:decisions.length});return json({rules,events,decisions});}return json({error:"Método não permitido."},405);};
export const config:Config={path:"/api/live-monitoring"};
