import type { Config, Context } from "@netlify/functions";
import { getDatabase } from "@netlify/database";
import { getSessionUser } from "../lib/auth.js";
import { getPortfolioForUser, logActivity } from "../lib/data.js";
import { json } from "../lib/http.js";

const defaults={enabled:true,monitorMode:"all",warningMovePct:2,criticalMovePct:4,staleMinutes:30,browserNotifications:false};
function clamp(n:number,min:number,max:number,fallback:number){return Number.isFinite(n)?Math.max(min,Math.min(max,n)):fallback;}
function normalizeSettings(v:any={}){const warning=clamp(Number(v.warningMovePct),.1,20,2);return {enabled:v.enabled!==false,monitorMode:["all","favorites","portfolio"].includes(v.monitorMode)?v.monitorMode:"all",warningMovePct:warning,criticalMovePct:Math.max(warning,clamp(Number(v.criticalMovePct),.1,30,4)),staleMinutes:Math.trunc(clamp(Number(v.staleMinutes),5,1440,30)),browserNotifications:v.browserNotifications===true};}
function safeStatus(v:any){if(!v||typeof v!=="object"||Array.isArray(v))return{};return Object.fromEntries(Object.entries(v).slice(0,250).map(([k,x]:any)=>[String(k).slice(0,180),{acknowledgedAt:typeof x?.acknowledgedAt==="string"?x.acknowledgedAt:null,mutedUntil:typeof x?.mutedUntil==="string"?x.mutedUntil:null}]));}
function safeHistory(v:any){if(!Array.isArray(v))return[];return v.slice(0,100).map((x:any)=>({id:String(x?.id||"").slice(0,180),severity:["critical","warning","info"].includes(x?.severity)?x.severity:"info",category:String(x?.category||"").slice(0,32),symbol:x?.symbol?String(x.symbol).slice(0,32):null,title:String(x?.title||"").slice(0,220),text:String(x?.text||"").slice(0,600),source:String(x?.source||"").slice(0,100),observedAt:x?.observedAt||null,createdAt:x?.createdAt||null})).filter((x:any)=>x.id&&x.title);}
export default async(req:Request,_context:Context)=>{const user=await getSessionUser(req);if(!user)return json({error:"Sessão expirada."},401);const portfolio=await getPortfolioForUser(user);if(!portfolio)return json({error:"Carteira não encontrada."},404);const portfolioId=Number(portfolio.id),db=getDatabase();if(req.method==="GET"){const rows=await db.sql`SELECT settings,alert_status,history,updated_at FROM live_alert_center WHERE portfolio_id=${portfolioId} LIMIT 1` as any[];const row=rows[0];return json({settings:normalizeSettings(row?.settings||defaults),status:safeStatus(row?.alert_status),history:safeHistory(row?.history),updatedAt:row?.updated_at||null});}if(req.method==="PUT"){let body:any;try{body=await req.json();}catch{return json({error:"Dados inválidos."},400);}const settings=normalizeSettings(body?.settings||{}),status=safeStatus(body?.status),history=safeHistory(body?.history);await db.sql`INSERT INTO live_alert_center(portfolio_id,settings,alert_status,history,updated_at) VALUES(${portfolioId},${JSON.stringify(settings)}::jsonb,${JSON.stringify(status)}::jsonb,${JSON.stringify(history)}::jsonb,NOW()) ON CONFLICT(portfolio_id) DO UPDATE SET settings=EXCLUDED.settings,alert_status=EXCLUDED.alert_status,history=EXCLUDED.history,updated_at=NOW()`;await logActivity(portfolioId,"updated","live_alert_center","Central de Alertas",{enabled:settings.enabled,monitorMode:settings.monitorMode,warningMovePct:settings.warningMovePct,criticalMovePct:settings.criticalMovePct});return json({settings,status,history});}return json({error:"Método não permitido."},405);};
export const config:Config={path:"/api/live-alerts"};
