import type { Config, Context } from "@netlify/functions";
import { getDatabase } from "@netlify/database";
import { getSessionUser } from "../lib/auth.js";
import { getPortfolioForUser, logActivity } from "../lib/data.js";
import { json } from "../lib/http.js";
function text(v:any,max:number){return String(v??"").slice(0,max);}
function iso(v:any){const d=new Date(String(v||""));return Number.isFinite(d.getTime())?d.toISOString():new Date().toISOString();}
function isoNull(v:any){if(!v)return null;const d=new Date(String(v));return Number.isFinite(d.getTime())?d.toISOString():null;}
function safeRecords(v:any){if(!Array.isArray(v))return[];return v.slice(0,50).map((x:any,i:number)=>({id:text(x?.id||`review-${i}`,180),createdAt:iso(x?.createdAt),createdBy:text(x?.createdBy||"Perfil",100),status:x?.status==="ATTENTION"?"ATTENTION":"REVIEWED",note:text(x?.note,1000),summary:{ok:Math.max(0,Number(x?.summary?.ok)||0),attention:Math.max(0,Number(x?.summary?.attention)||0),info:Math.max(0,Number(x?.summary?.info)||0),total:Math.max(0,Number(x?.summary?.total)||0)},checks:Array.isArray(x?.checks)?x.checks.slice(0,20).map((c:any)=>({key:text(c?.key,80),title:text(c?.title,180),status:["ok","attention","info"].includes(c?.status)?c.status:"info",detail:text(c?.detail,500),value:text(c?.value,120)})):[]}));}
function safeCases(v:any){if(!Array.isArray(v))return[];return v.slice(0,200).map((x:any,i:number)=>({id:text(x?.id||`case-${i}`,180),sourceType:["check","position","manual"].includes(x?.sourceType)?x.sourceType:"manual",sourceKey:text(x?.sourceKey,180),sourceSnapshot:x?.sourceSnapshot&&typeof x.sourceSnapshot==="object"?x.sourceSnapshot:{},title:text(x?.title||"Caso de conciliação",180),status:["OPEN","INVESTIGATING","RESOLVED","DISMISSED"].includes(x?.status)?x.status:"OPEN",classification:["UNCLASSIFIED","DATA_ENTRY","TIMING","SOURCE_GAP","DUPLICATE","ROUNDING","OTHER"].includes(x?.classification)?x.classification:"UNCLASSIFIED",dueDate:x?.dueDate?text(x.dueDate,10):null,analysis:text(x?.analysis,2000),evidence:text(x?.evidence,2000),resolution:text(x?.resolution,2000),createdAt:iso(x?.createdAt),createdBy:text(x?.createdBy||"Perfil",100),updatedAt:iso(x?.updatedAt||x?.createdAt),updatedBy:text(x?.updatedBy||x?.createdBy||"Perfil",100),resolvedAt:isoNull(x?.resolvedAt),resolvedBy:text(x?.resolvedBy,100)})).filter((x:any)=>x.id&&x.title);}
export default async(req:Request,_context:Context)=>{const user=await getSessionUser(req);if(!user)return json({error:"Sessão expirada."},401);const portfolio=await getPortfolioForUser(user);if(!portfolio)return json({error:"Carteira não encontrada."},404);const portfolioId=Number(portfolio.id),db=getDatabase();if(req.method==="GET"){const rows=await db.sql`SELECT records,cases,updated_at FROM reconciliation_center WHERE portfolio_id=${portfolioId} LIMIT 1` as any[];return json({records:safeRecords(rows[0]?.records),cases:safeCases(rows[0]?.cases),updatedAt:rows[0]?.updated_at||null});}if(req.method==="PUT"){let body:any;try{body=await req.json();}catch{return json({error:"Dados inválidos."},400);}const records=safeRecords(body?.records),cases=safeCases(body?.cases);await db.sql`INSERT INTO reconciliation_center(portfolio_id,records,cases,updated_at) VALUES(${portfolioId},${JSON.stringify(records)}::jsonb,${JSON.stringify(cases)}::jsonb,NOW()) ON CONFLICT(portfolio_id) DO UPDATE SET records=EXCLUDED.records,cases=EXCLUDED.cases,updated_at=NOW()`;const activeCases=cases.filter((c:any)=>c.status==="OPEN"||c.status==="INVESTIGATING").length;await logActivity(portfolioId,"updated","reconciliation_center","Resolution Desk",{records:records.length,cases:cases.length,activeCases,lastStatus:records[0]?.status||null});return json({records,cases});}return json({error:"Método não permitido."},405);};
export const config:Config={path:"/api/reconciliation"};
